# -*- coding: utf-8 -*-
"""QR scanner Projects

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-OYEPtgcYbX_k-ezcRyDmwrx2x4-3VU9

**QR code**
"""

!pip install qrcode

import qrcode as qc
image= qc.make("www.google.com")
image.save("google.png")